//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GhPlotLib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GhPlotLib.Resources.texts", typeof(texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # -*- coding: utf-8 -*-
        ///&quot;&quot;&quot;
        ///Created on Sat Jun 10 22:21:15 2017
        ///
        ///@author: Mahmoud Abdelrahman
        ///&quot;&quot;&quot;
        ///
        ///workingDir = ##workingDir##
        ///logfile = open(workingDir+&quot;logfile.txt&quot;, &apos;w&apos;)
        ///separator = &quot; -------------------------------- \n&quot;
        ///logtext = &quot;&quot;
        ///logtext += &quot; (C) author: Mahmoud Abdelrahman 2017 \n all rights reserved 2017\n &lt;arch.mahmoud.ouf111@gmail.com&gt;\n&quot;
        ///logtext += separator
        ///try:
        ///    import numpy as np
        ///    logtext += &quot;NumPy successfully imported\n&quot;
        ///    logtext += &quot;NumPy version : &quot;+ (str(np.__ver [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _initNumpyMatplotLib {
            get {
                return ResourceManager.GetString("_initNumpyMatplotLib", resourceCulture);
            }
        }
    }
}
